### ISSUE TITLE
Couldn't not find upstream branch 'origin/22.1' and tag '22.1'

### ISSUE THREAD

**Issue by jpopelka** [packit/hardly#61]
https://gitlab.com/redhat/centos-stream/src/cloud-init/-/merge_requests/24

```
 Running handler <hardly.handlers.distgit.DistGitMRHandler object at 0x7f980aea8a60> for task.run_dist_git_pr_handler
 About to create a dist-git MR from source-git MR https://gitlab.com/redhat/centos-stream/src/cloud-init/-/merge_requests/24
 Arguments received in the init method of the LocalProject class: 
git_repo: None
working_dir: /tmp/sandcastle
ref: 5f10e6cf63bfa94f705e5490459db9bee161768c
git_project: GitlabProject(namespace="eesposit", repo="cloud-init-centos-")
git_service: None
git_url: 
full_name: 
namespace: 
repo_name: 
offline: False
refresh True
remote: 
pr_id: None
cache: None
merge_pr: True
target_branch: 

 `working_dir` is set and `git_repo` is not: let's discover...
 Parsed service GitlabService(instance_url='https://gitlab.com', token='***') from the project GitlabProject(namespace="eesposit", repo="cloud-init-centos-").
 `working_dir` is set and `git_repo` is not: let's discover...
 Parsed remote url 'https://gitlab.com/eesposit/cloud-init-centos-.git' from the project GitlabProject(namespace="eesposit", repo="cloud-init-centos-").
 `working_dir` is set and `git_repo` is not: let's discover...
 INFO/ForkPoolWorker-1] Cloning repo https://gitlab.com/eesposit/cloud-init-centos-.git -> /tmp/sandcastle
 Popen(['git', 'clone', '--tags', '-v', 'https://gitlab.com/eesposit/cloud-init-centos-.git', '/tmp/sandcastle'], cwd=/src, universal_newlines=True, shell=None, istream=None)
 Cmd(['git', 'clone', '--tags', '-v', 'https://gitlab.com/eesposit/cloud-init-centos-.git', '/tmp/sandcastle'])'s unused stdout: 
 We just cloned git repo https://gitlab.com/eesposit/cloud-init-centos-.git to /tmp/sandcastle.
 Parsed repo name 'cloud-init-centos-' from the git project GitlabProject(namespace="eesposit", repo="cloud-init-centos-").
 Parsed namespace 'eesposit' from the project GitlabProject(namespace="eesposit", repo="cloud-init-centos-").
 Parsed full repo name 'eesposit/cloud-init-centos-'.
 INFO/ForkPoolWorker-1] Checking out ref '5f10e6cf63bfa94f705e5490459db9bee161768c'.
 Popen(['git', 'checkout', '5f10e6cf63bfa94f705e5490459db9bee161768c'], cwd=/tmp/sandcastle, universal_newlines=False, shell=None, istream=None)
 Popen(['git', 'cat-file', '--batch-check'], cwd=/tmp/sandcastle, universal_newlines=False, shell=None, istream=<valid stream>)
 Current commit is '5f10e6cf63bfa94f705e5490459db9bee161768c'
 Command: centpkg -q clone --anonymous cloud-init /tmp/packit-dist-gitcks22v0i
 Arguments received in the init method of the LocalProject class: 
git_repo: None
working_dir: /tmp/packit-dist-gitcks22v0i
ref: 
git_project: GitlabProject(namespace="redhat/centos-stream/rpms", repo="cloud-init")
git_service: None
git_url: https://gitlab.com/redhat/centos-stream/rpms/cloud-init.git
full_name: 
namespace: redhat/centos-stream/rpms
repo_name: cloud-init
offline: False
refresh True
remote: 
pr_id: None
cache: None
merge_pr: True
target_branch: 

 Parsed full repo name 'redhat/centos-stream/rpms/cloud-init'.
 `working_dir` is set and `git_repo` is not: let's discover...
 It's a git repo!
 Parsed service GitlabService(instance_url='https://gitlab.com', token='***') from the project GitlabProject(namespace="redhat/centos-stream/rpms", repo="cloud-init").
 Parsed ref 'c9s' from the repo <git.repo.base.Repo '/tmp/packit-dist-gitcks22v0i/.git'>.
 ERROR/ForkPoolWorker-1] Patch 0006-rhel-cloud.cfg-remove-ssh_genkeytypes-in-settings.py.patch does not exist
 ERROR/ForkPoolWorker-1] Patch 0005-limit-permissions-on-def_log_file.patch does not exist
 ERROR/ForkPoolWorker-1] Patch 0004-Setting-highest-autoconnect-priority-for-network-scr.patch does not exist
 ERROR/ForkPoolWorker-1] Patch 0003-Adding-_netdev-to-the-default-mount-configuration.patch does not exist
 ERROR/ForkPoolWorker-1] Patch 0002-Do-not-write-NM_CONTROLLED-no-in-generated-interface.patch does not exist
 ERROR/ForkPoolWorker-1] Patch 0001-Add-initial-redhat-changes.patch does not exist
 INFO/ForkPoolWorker-1] Version in spec file is '22.1'.
 Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=None)
 Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=None)
 Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/tmp/sandcastle, universal_newlines=False, shell=None, istream=None)
 Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/tmp/sandcastle, universal_newlines=False, shell=None, istream=None)
 No ref given or is not glob pattern
 INFO/ForkPoolWorker-1] We will not check out the upstream tag because this is a source-git repo.
Running ActionName.post_upstream_clone hook.
 Running ActionName.post_upstream_clone.
 Running default implementation for ActionName.post_upstream_clone.
 INFO/ForkPoolWorker-1] Version in spec file is '22.1'.
 Allowed GPG keys are not set, skipping the verification.
 Running ActionName.pre_sync hook.
 Running ActionName.pre_sync.
 Running default implementation for ActionName.pre_sync.
 It seems that branch 'c9s' already exists, checking it out.
 INFO/ForkPoolWorker-1] Using 'c9s' dist-git branch.
 About to update branch 'c9s'.
 Popen(['git', 'fetch', '-v', 'origin'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=True, shell=None, istream=None)
 Popen(['git', 'cat-file', '--batch-check'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=<valid stream>)
 Checking out branch c9s.
 Popen(['git', 'checkout', 'c9s'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=None)
 Checking out branch 22.1-c9s-src-24.
 Popen(['git', 'checkout', '22.1-c9s-src-24'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=None)
 README: /tmp/packit-dist-gitcks22v0i/README.packit
 Running ActionName.prepare_files.
 Running default implementation for ActionName.prepare_files.
 Running ['rsync', '--archive', '--delete', '--filter', 'protect .git*', '--filter', 'protect sources', '--filter', 'exclude source-git.yaml', '--filter', 'exclude .gitignore', '--filter', 'exclude rpmbuild', '--filter', 'exclude scripts', '--filter', 'exclude Makefile*', '--ignore-missing-args', '/tmp/sandcastle/.distro/', '/tmp/packit-dist-gitcks22v0i'] ...
 Command: rsync --archive --delete --filter protect .git* --filter protect sources --filter exclude source-git.yaml --filter exclude .gitignore --filter exclude rpmbuild --filter exclude scripts --filter exclude Makefile* --ignore-missing-args /tmp/sandcastle/.distro/ /tmp/packit-dist-gitcks22v0i
 Running ActionName.create_patches.
 Running default implementation for ActionName.create_patches.
 Popen(['git', 'reset', '--hard', 'HEAD'], cwd=/tmp/packit-dist-gitcks22v0i, universal_newlines=False, shell=None, istream=None)
 INFO/ForkPoolWorker-1] Cleaning up the mess.
 Removing contents of the PV.
 INFO/ForkPoolWorker-1] Volume is not empty.
 Content: ['.git', '.distro', '.github', '.readthedocs.yaml', 'LICENSE', 'LICENSE-Apache2.0', 'LICENSE-GPLv3', 'MANIFEST.in', 'SECURITY.md', 'TODO.rst', 'bash_completion', 'cloudinit', 'config', 'doc', 'packages', 'rhel', 'snapcraft.yaml', 'systemd', 'sysvinit', 'templates', 'tests', 'tools', 'udev', 'upstart', '.git-blame-ignore-revs', '.gitignore', '.pylintrc', '.travis.yml', 'CONTRIBUTING.rst', 'ChangeLog', 'Makefile', 'README.md', 'conftest.py', 'doc-requirements.txt', 'integration-requirements.txt', 'pyproject.toml', 'requirements.txt', 'setup.py', 'test-requirements.txt', 'tox.ini']
 ERROR/ForkPoolWorker-1] Task TaskName.dist_git_pr[58e342c8-46c8-4734-a9d0-3c76564c3010] raised unexpected: PackitException("Couldn't not find upstream branch 'origin/22.1' and tag '22.1'.")
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 200, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 195, in _inner
    return f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/lib/python3.10/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/src/hardly/tasks.py", line 90, in run_dist_git_sync_handler
    return get_handlers_task_results(handler.run_job(), event)
  File "/usr/local/lib/python3.10/site-packages/packit_service/worker/handlers/abstract.py", line 369, in run_job
    job_results[result_key] = self.run_n_clean()
  File "/usr/local/lib/python3.10/site-packages/packit_service/worker/handlers/abstract.py", line 267, in run_n_clean
    return self.run()
  File "/src/hardly/handlers/distgit.py", line 107, in run
    dg_mr = self.api.sync_release(
  File "/usr/local/lib/python3.10/site-packages/packit/api.py", line 764, in sync_release
    self.update_dist_git(
  File "/usr/local/lib/python3.10/site-packages/packit/api.py", line 267, in update_dist_git
    patches = self.up.create_patches(
  File "/usr/local/lib/python3.10/site-packages/packit/upstream.py", line 213, in create_patches
    return pg.create_patches(
  File "/usr/local/lib/python3.10/site-packages/packit/patches.py", line 795, in create_patches
    contained = self.are_child_commits_contained(git_ref)
  File "/usr/local/lib/python3.10/site-packages/packit/patches.py", line 385, in are_child_commits_contained
    commits = self.get_commits_since_ref(
  File "/usr/local/lib/python3.10/site-packages/packit/patches.py", line 847, in get_commits_since_ref
    raise PackitException(
packit.exceptions.PackitException: Couldn't not find upstream branch 'origin/22.1' and tag '22.1'.
```

**Comment by csomh** [comment]
Isn't this happening, b/c the fork is cloned instead of the target repo, and the fork is missing some of the tags the target repo does have?

**Comment by jpopelka** [comment]
You're goddamn right Mr @csomh 
And I first discarded that option because I had already checked the tags in both repos ([upstream](https://gitlab.com/redhat/centos-stream/src/cloud-init/-/tags) and [fork](https://gitlab.com/eesposit/cloud-init-centos-/-/tags)) and they were there.
Only now have I spotted that one of them is the `22.1` and the second (in the fork) is actually `21.1` and there's no `22.1` in the fork, indeed :man_facepalming: 
The same applies to https://gitlab.com/redhat/centos-stream/src/seabios/-/merge_requests/3 where [upstream has rel-1.16.0 tag](https://gitlab.com/redhat/centos-stream/src/seabios/-/tags), but the [fork has not](https://gitlab.com/kraxel/centos-seabios/-/tags).

Ok, so we have a culprit, but how do we prevent this from happening?
How do we make people not forget to fetch tags as well?

**Comment by LaneWolf** [comment]
Why are you working with fork? It should be expected this repo will not have all necessary tags as developers use it as push only - pushing just the branch they need for MR. All the tags should be in target repo.

**Comment by csomh** [comment]
> Ok, so we have a culprit, but how do we prevent this from happening? How do we make people not forget to fetch tags as well?

Doesn't the webhook payload the bot receives also contain the upstream Git URL? We need to clone that repository first, and only then fetch and checkout the branch of the MR.
